version: "3.9"

services:
  app:
    build: .
    container_name: hotelextv
    ports:
      - "3003:3000"
    environment:
      DATABASE_URL: "mysql://micro:Nextjs.2024@192.168.145.20:3306/extensions"
      NEXTAUTH_SECRET: "dikr3FJ9I2HG408GF24G...hroigsfa8s7af09auijhf3208fhi2o"
      JWT_SECRET: "dikr3FJ9I2HG408GF24G...hroigsfa8s7af09auijhf3208fhi2o"
      NEXT_PUBLIC_SECRET_KEY: "fec3ee9596164653946d66b88a7b1d7041b1b73cb6337686743c984a173e92da"
      API_AUTH_TOKEN: "q4vf9p8n4907895f7m8d24m75c2q947m2398c574q9586c490q756c98q4m705imtugcfecvrhym04capwz3e2ewqaefwegfiuoamv4ros2nuyp0sjc3iutow924bn5ry943utrjmi"
      CLOUDINARY_CLOUD_NAME: "dp6iart4f"
      CLOUDINARY_API_KEY: "454833539123464"
      CLOUDINARY_API_SECRET: "G0B2GwHxFsqDQL5qMbNZ1FHUH_k"
    restart: always